// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Devices          string
	Methods          string
	RoleMethods      string
	Roles            string
	UserDevices      string
	UserWorkspaces   string
	Users            string
	WorkspaceDevices string
	Workspaces       string
}{
	Devices:          "devices",
	Methods:          "methods",
	RoleMethods:      "role_methods",
	Roles:            "roles",
	UserDevices:      "user_devices",
	UserWorkspaces:   "user_workspaces",
	Users:            "users",
	WorkspaceDevices: "workspace_devices",
	Workspaces:       "workspaces",
}
