// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMethods(t *testing.T) {
	t.Parallel()

	query := Methods()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMethodsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMethodsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Methods().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMethodsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MethodSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMethodsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MethodExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Method exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MethodExists to return true, but got false.")
	}
}

func testMethodsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	methodFound, err := FindMethod(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if methodFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMethodsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Methods().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMethodsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Methods().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMethodsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	methodOne := &Method{}
	methodTwo := &Method{}
	if err = randomize.Struct(seed, methodOne, methodDBTypes, false, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}
	if err = randomize.Struct(seed, methodTwo, methodDBTypes, false, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = methodOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = methodTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Methods().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMethodsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	methodOne := &Method{}
	methodTwo := &Method{}
	if err = randomize.Struct(seed, methodOne, methodDBTypes, false, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}
	if err = randomize.Struct(seed, methodTwo, methodDBTypes, false, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = methodOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = methodTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func methodBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func methodAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Method) error {
	*o = Method{}
	return nil
}

func testMethodsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Method{}
	o := &Method{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, methodDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Method object: %s", err)
	}

	AddMethodHook(boil.BeforeInsertHook, methodBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	methodBeforeInsertHooks = []MethodHook{}

	AddMethodHook(boil.AfterInsertHook, methodAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	methodAfterInsertHooks = []MethodHook{}

	AddMethodHook(boil.AfterSelectHook, methodAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	methodAfterSelectHooks = []MethodHook{}

	AddMethodHook(boil.BeforeUpdateHook, methodBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	methodBeforeUpdateHooks = []MethodHook{}

	AddMethodHook(boil.AfterUpdateHook, methodAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	methodAfterUpdateHooks = []MethodHook{}

	AddMethodHook(boil.BeforeDeleteHook, methodBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	methodBeforeDeleteHooks = []MethodHook{}

	AddMethodHook(boil.AfterDeleteHook, methodAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	methodAfterDeleteHooks = []MethodHook{}

	AddMethodHook(boil.BeforeUpsertHook, methodBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	methodBeforeUpsertHooks = []MethodHook{}

	AddMethodHook(boil.AfterUpsertHook, methodAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	methodAfterUpsertHooks = []MethodHook{}
}

func testMethodsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMethodsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(methodColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMethodToManyRoleMethods(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Method
	var b, c RoleMethod

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, roleMethodDBTypes, false, roleMethodColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, roleMethodDBTypes, false, roleMethodColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.MethodID = a.ID
	c.MethodID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.RoleMethods().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.MethodID == b.MethodID {
			bFound = true
		}
		if v.MethodID == c.MethodID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := MethodSlice{&a}
	if err = a.L.LoadRoleMethods(ctx, tx, false, (*[]*Method)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RoleMethods); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RoleMethods = nil
	if err = a.L.LoadRoleMethods(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RoleMethods); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMethodToManyAddOpRoleMethods(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Method
	var b, c, d, e RoleMethod

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, methodDBTypes, false, strmangle.SetComplement(methodPrimaryKeyColumns, methodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*RoleMethod{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, roleMethodDBTypes, false, strmangle.SetComplement(roleMethodPrimaryKeyColumns, roleMethodColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*RoleMethod{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRoleMethods(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.MethodID {
			t.Error("foreign key was wrong value", a.ID, first.MethodID)
		}
		if a.ID != second.MethodID {
			t.Error("foreign key was wrong value", a.ID, second.MethodID)
		}

		if first.R.Method != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Method != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RoleMethods[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RoleMethods[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RoleMethods().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMethodsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMethodsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MethodSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMethodsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Methods().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	methodDBTypes = map[string]string{`ID`: `int`, `MethodName`: `varchar`}
	_             = bytes.MinRead
)

func testMethodsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(methodPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(methodAllColumns) == len(methodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, methodDBTypes, true, methodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMethodsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(methodAllColumns) == len(methodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Method{}
	if err = randomize.Struct(seed, o, methodDBTypes, true, methodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, methodDBTypes, true, methodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(methodAllColumns, methodPrimaryKeyColumns) {
		fields = methodAllColumns
	} else {
		fields = strmangle.SetComplement(
			methodAllColumns,
			methodPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MethodSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMethodsUpsert(t *testing.T) {
	t.Parallel()

	if len(methodAllColumns) == len(methodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLMethodUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Method{}
	if err = randomize.Struct(seed, &o, methodDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Method: %s", err)
	}

	count, err := Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, methodDBTypes, false, methodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Method struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Method: %s", err)
	}

	count, err = Methods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
