// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Devices", testDevicesUpsert)

	t.Run("Methods", testMethodsUpsert)

	t.Run("RoleMethods", testRoleMethodsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("UserDevices", testUserDevicesUpsert)

	t.Run("UserWorkspaces", testUserWorkspacesUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("WorkspaceDevices", testWorkspaceDevicesUpsert)

	t.Run("Workspaces", testWorkspacesUpsert)
}
