// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserDevices(t *testing.T) {
	t.Parallel()

	query := UserDevices()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserDevicesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserDevicesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserDevices().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserDevicesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserDeviceSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserDevicesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserDeviceExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserDevice exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserDeviceExists to return true, but got false.")
	}
}

func testUserDevicesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userDeviceFound, err := FindUserDevice(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userDeviceFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserDevicesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserDevices().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserDevicesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserDevices().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserDevicesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userDeviceOne := &UserDevice{}
	userDeviceTwo := &UserDevice{}
	if err = randomize.Struct(seed, userDeviceOne, userDeviceDBTypes, false, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}
	if err = randomize.Struct(seed, userDeviceTwo, userDeviceDBTypes, false, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userDeviceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userDeviceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserDevices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserDevicesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userDeviceOne := &UserDevice{}
	userDeviceTwo := &UserDevice{}
	if err = randomize.Struct(seed, userDeviceOne, userDeviceDBTypes, false, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}
	if err = randomize.Struct(seed, userDeviceTwo, userDeviceDBTypes, false, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userDeviceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userDeviceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userDeviceBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func userDeviceAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserDevice) error {
	*o = UserDevice{}
	return nil
}

func testUserDevicesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserDevice{}
	o := &UserDevice{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userDeviceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserDevice object: %s", err)
	}

	AddUserDeviceHook(boil.BeforeInsertHook, userDeviceBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userDeviceBeforeInsertHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.AfterInsertHook, userDeviceAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userDeviceAfterInsertHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.AfterSelectHook, userDeviceAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userDeviceAfterSelectHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.BeforeUpdateHook, userDeviceBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userDeviceBeforeUpdateHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.AfterUpdateHook, userDeviceAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userDeviceAfterUpdateHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.BeforeDeleteHook, userDeviceBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userDeviceBeforeDeleteHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.AfterDeleteHook, userDeviceAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userDeviceAfterDeleteHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.BeforeUpsertHook, userDeviceBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userDeviceBeforeUpsertHooks = []UserDeviceHook{}

	AddUserDeviceHook(boil.AfterUpsertHook, userDeviceAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userDeviceAfterUpsertHooks = []UserDeviceHook{}
}

func testUserDevicesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserDevicesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userDeviceColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserDeviceToOneDeviceUsingDevice(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserDevice
	var foreign Device

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userDeviceDBTypes, false, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, deviceDBTypes, false, deviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Device struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.DeviceID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Device().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserDeviceSlice{&local}
	if err = local.L.LoadDevice(ctx, tx, false, (*[]*UserDevice)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Device == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Device = nil
	if err = local.L.LoadDevice(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Device == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserDeviceToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserDevice
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userDeviceDBTypes, false, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserDeviceSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*UserDevice)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserDeviceToOneSetOpDeviceUsingDevice(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserDevice
	var b, c Device

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userDeviceDBTypes, false, strmangle.SetComplement(userDevicePrimaryKeyColumns, userDeviceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, deviceDBTypes, false, strmangle.SetComplement(devicePrimaryKeyColumns, deviceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, deviceDBTypes, false, strmangle.SetComplement(devicePrimaryKeyColumns, deviceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Device{&b, &c} {
		err = a.SetDevice(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Device != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserDevices[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.DeviceID != x.ID {
			t.Error("foreign key was wrong value", a.DeviceID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DeviceID))
		reflect.Indirect(reflect.ValueOf(&a.DeviceID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.DeviceID != x.ID {
			t.Error("foreign key was wrong value", a.DeviceID, x.ID)
		}
	}
}
func testUserDeviceToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserDevice
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userDeviceDBTypes, false, strmangle.SetComplement(userDevicePrimaryKeyColumns, userDeviceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserDevices[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserDevicesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserDevicesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserDeviceSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserDevicesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserDevices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userDeviceDBTypes = map[string]string{`UserID`: `int`, `DeviceID`: `int`, `ID`: `int`}
	_                 = bytes.MinRead
)

func testUserDevicesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userDevicePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userDeviceAllColumns) == len(userDevicePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDevicePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserDevicesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userDeviceAllColumns) == len(userDevicePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserDevice{}
	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDeviceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userDeviceDBTypes, true, userDevicePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userDeviceAllColumns, userDevicePrimaryKeyColumns) {
		fields = userDeviceAllColumns
	} else {
		fields = strmangle.SetComplement(
			userDeviceAllColumns,
			userDevicePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserDeviceSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserDevicesUpsert(t *testing.T) {
	t.Parallel()

	if len(userDeviceAllColumns) == len(userDevicePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLUserDeviceUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserDevice{}
	if err = randomize.Struct(seed, &o, userDeviceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserDevice: %s", err)
	}

	count, err := UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userDeviceDBTypes, false, userDevicePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserDevice struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserDevice: %s", err)
	}

	count, err = UserDevices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
