version: '2'

services:
  device1:
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - REGION=${REGION}
      - REGISTRY_ID=${REGISTRY_ID}
      - DEVICE_ID=device-one
      - PRIVATE_KEY_PATH=/app/ec_private.pem
      - ALGORITHM=${ALGORITHM}
    build: ./device
    volumes:
      - ${PWD}/deviceKeys/device1/ec_private.pem:/app/ec_private.pem
  device2:
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - REGION=${REGION}
      - REGISTRY_ID=${REGISTRY_ID}
      - DEVICE_ID=device-two
      - PRIVATE_KEY_PATH=/app/ec_private.pem
      - ALGORITHM=${ALGORITHM}
    build: ./device
    volumes:
      - ${PWD}/deviceKeys/device2/ec_private.pem:/app/ec_private.pem
  device3:
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - REGION=${REGION}
      - REGISTRY_ID=${REGISTRY_ID}
      - DEVICE_ID=device-three
      - PRIVATE_KEY_PATH=/app/ec_private.pem
      - ALGORITHM=${ALGORITHM}
    build: ./device
    volumes:
      - ${PWD}/deviceKeys/device3/ec_private.pem:/app/ec_private.pem
  auth-svc:
    build: ./auth-svc
    ports:
      - "8081"
  orca-svc:
    build: ./orca-svc
    ports:
      - "8080"
  redis:
    image: redis